# [s2d1, s2d4, s2d5]
# [s3d1, s3d6, s3d7]
data:
  task_type: cite_pre
  train_batches: [s1d1, s1d2, s1d3]
  test_batches: []
  batch_correct: [s1d1, s1d2, s1d3]
  val_size: 0
  batch_size: 32
  mod1:
    name: gex
    use_normalized: True
    scale: False
    l2_norm: False
    gene_path: data/genes.csv
    gene_fraction: 1.0
  mod2:
    name: adt
    use_normalized: True
    scale: False
    l2_norm: False
  mixup: 0.0

model:
  first:
    dim: [1000, 500]
    dropout: 0.0
  second:
    dim: [100, 70, 50]
    dropout: 0.0
  common_dim: [150]
  activation: leaky_relu
  lr: 0.001
  attack: 10
  sustain: 3000
  release: 100
  gradient_clip: 1.0

  use_mmd_loss: True
  mmd_lambda: 0.2

  use_l2_loss: False
  l2_loss_lambda: 0.0

  use_coral_loss: False
  coral_lambda: 0.0

  use_critic: False
  critic_lambda: 0.03
  critic_dims: [75, 30]
  normal_iterations: 1
  critic_iterations: 1
  critic_lr: 0.001