data:
  task_type: cite_pre
  train_batches: [s1d1, s1d2, s2d4, s2d1]
  test_batches: [s3d7, s3d6]
  batch_correct: []
  val_size: 0
  batch_size: 32
  mod1:
    name: gex
    use_normalized: True
    scale: False
    l2_norm: False
    gene_path: data/genes.csv
    gene_fraction: 1.0
  mod2:
    name: adt
    use_normalized: True
    scale: False
    l2_norm: False
  mixup: 0.0

model:
  first_dim: [1000, 1000, 500, 250, 100]
  second_dim: [100, 70, 50]
  common_dim: [150, 150, 125, 100, 100]
  activation: leaky_relu
  lr: 0.001
  attack: 10
  sustain: 3000
  release: 100
  gradient_clip: 1.0

  use_mmd_loss: False
  mmd_lambda: 0.1

  use_l2_loss: False
  l2_loss_lambda: 0.0

  use_coral_loss: False
  coral_lambda: 0.0

  use_critic: False
  critic_lambda: 0.03
  critic_dims: [75, 30]
  normal_iterations: 1
  critic_iterations: 1
  critic_lr: 0.001