data: 
  dataset_name: mm/official/adt_to_gex
  task_type: adt_to_gex
  train_batches: [s1d1, s2d4, s2d1, s3d6]
  test_batches: [s1d2, s3d7]
  batch_correct: []
  val_size: 512
  gene_fraction: 0.1
  mod1:
    name: adt
    use_normalized: True
    scale: True
    type: float
  mod2:
    name: gex
    use_normalized: True
    scale: True
    type: float



model:
  second_dim: [150, 150, 100, 75, 50]
  first_dim: [1000, 900, 750, 300, 200, 100, 50]
  latent_dim: 30
  activation: leaky_relu
  lr: 0.001
  batch_size: 32
  attack: 10
  sustain: 700
  release: 100
  gradient_clip: 1.0
  train_per_batch: False
  train_temperature: 3.0
  predict_temperature: 3.0
  l2_lambda: 0.0