data: 
  task_type: adt_to_gex
  train_batches: [s1d1, s1d2, s2d1, s2d4]
  test_batches: [s3d6, s3d7]
  batch_correct: []
  val_size: 512
  batch_size: 128
  mod1:
    name: adt
    use_normalized: True
    scale: False
  mod2:
    name: gex
    use_normalized: True
    scale: False
    gene_path: data/genes.csv
    gene_fraction: 0.1



model:
  first_dim: [100, 100]
  first_dropout: []
  first_batchnorm: [0, 1]
  second_dim: [500, 250, 50]
  second_dropout: []
  second_batchnorm: [0, 1, 2, 3]
  dropout: 0.5
  enter_dropout: 0.8
  latent_dim: 25
  activation: leaky_relu
  lr: 0.001
  attack: 10
  sustain: 700
  release: 100
  gradient_clip: 1.0
  train_per_batch: False
  train_temperature: 5.0
  predict_temperature: 9.0
  l2_lambda: 0.0007