data: 
  task_type: atac_to_gex
  train_batches: [s1d1, s1d2, s2d1, s2d4]
  test_batches: [s3d6, s3d7]
  batch_correct: []
  val_size: 512
  batch_size: 32
  mod1:
    name: atac
    scale: True
    mapping_file: data/region_to_gene.csv
    use_gene_activity: True
    window: 100
  mod2:
    name: gex
    use_normalized: True
    scale: True



model:
  first_dim: [1000, 900, 750, 300, 200, 100, 50]
  first_dropout: []
  second_dim: [1000, 900, 750, 300, 200, 100, 50]
  second_dropout: []
  dropout: 0.5
  latent_dim: 30
  activation: leaky_relu
  lr: 0.001
  attack: 10
  sustain: 700
  release: 100
  gradient_clip: 1.0
  train_per_batch: False
  train_temperature: 3.0
  predict_temperature: 9.0
  l2_lambda: 0.0