data: 
  task_type: atac_to_gex
  train_batches: [s1d1, s1d2, s2d1, s2d4]
  test_batches: [s3d6]
  batch_correct: []
  val_size: 512
  batch_size: 32
  mod1:
    name: atac
    scale: True
    mapping_file: data/region_to_gene.csv
    use_gene_activity: False
    window: 10
  mod2:
    name: gex
    use_normalized: True
    scale: True



model:
  first_dim: [1000, 500, 250, 50]
  first_dropout: []
  first_batchnorm: [0, 1, 2, 3, 4]
  second_dim: [1000, 500, 250, 50]
  second_dropout: []
  second_batchnorm: [0, 1, 2, 3, 4]
  dropout: 0.0
  enter_dropout: 0.7
  latent_dim: 25
  activation: leaky_relu
  lr: 0.001
  attack: 10
  sustain: 700
  release: 100
  gradient_clip: 1.0
  train_per_batch: False
  train_temperature: 5.0
  predict_temperature: 9.0
  l2_lambda: 0.0002