# All Batches: ['s1d1', 's1d2', 's1d3', 's2d1', 's2d4', 's2d5', 's3d10', 's3d3', 's3d6', 's3d7']
data: 
  task_type: atac_to_gex
  train_batches: [s1d1, s1d2, s1d3, s2d1, s2d4, s2d5]
  test_batches: [s3d3, s3d6, s3d7]
  batch_correct: []
  val_size: 512
  batch_size: 256
  mod1:
    name: atac
    scale: False
    mapping_file: data/region_to_gene.csv
    use_gene_activity: False
    window: 7
  mod2:
    name: gex
    use_normalized: True
    scale: False
    l2_norm: False
  mixup: 0.1



model:
  first:
    dim: [1000, 300, 100, 40]
    dropout_pos: []
    dropout_p: 0.0
    batchnorm: [0, 1, 2, 3, 4]
    entry_dropout:
      type: standard
      p: 0.7
    log_transform: False
  second:
    dim: [500, 100, 100, 40]
    dropout_pos: []
    dropout_p: 0.0
    batchnorm: [0, 1, 2, 3, 4]
    entry_dropout:
      type: standard
      p: 0.7
    log_transform: False
  latent_dim: 15
  activation: leaky_relu
  lr: 0.0005
  attack: 10
  sustain: 700
  release: 100
  gradient_clip: 1.0
  train_per_batch: True
  train_temperature: -1
  predict_temperature: 3
  l2_lambda: 0.0001