# All Batches: [s1d1, s1d2, s1d3, s2d1, s2d4, s2d5, s3d6, s3d7]
data: 
  task_type: gex_to_atac
  train_batches: [s1d1, s1d2, s2d1, s2d4]
  test_batches: [s3d6]
  batch_correct: []
  val_size: 512
  batch_size: 256
  mod1:
    name: gex
    use_normalized: True
    scale: False
    l2_norm: False
  mod2:
    name: atac
    scale: False
    mapping_file: data/region_to_gene.csv
    use_gene_activity: False
    window: 5
  mixup: 0.0



model:
  first_dim: [200, 100, 100, 40]
  first_dropout: []
  first_batchnorm: [0, 1, 2, 3, 4]
  second_dim: [200, 100, 100, 40]
  second_dropout: []
  second_batchnorm: [0, 1, 2, 3, 4]
  dropout: 0.0
  enter_dropout: 0.9
  latent_dim: 20
  activation: leaky_relu
  lr: 0.0005
  attack: 10
  sustain: 700
  release: 100
  gradient_clip: 1.0
  train_per_batch: True
  train_temperature: -1
  predict_temperature: 2
  l2_lambda: 0.0002