data: 
  task_type: gex_to_adt
  train_batches: [s1d1, s1d2, s2d1, s2d4]
  test_batches: [s3d6, s3d7]
  batch_correct: []
  val_size: 512
  batch_size: 32
  mod1:
    name: gex
    use_normalized: True
    scale: True
    gene_path: data/genes.csv
    gene_fraction: 0.1
  mod2:
    name: adt
    use_normalized: True
    scale: True


model:
  first_dim: [1000, 750, 300, 200, 100, 50]
  first_dropout: [1, 3, 5]
  second_dim: [150, 100, 75, 50]
  second_dropout: [1]
  dropout: 0.0
  latent_dim: 75
  activation: relu
  lr: 0.0005
  batch_size: 32
  attack: 10
  sustain: 700
  release: 100
  gradient_clip: 1.0
  train_per_batch: False
  train_temperature: 5.0
  predict_temperature: 10.6
  l2_lambda: 0.0005