# All Batches: [s1d1, s1d2, s1d3, s2d1, s2d4, s2d5, s3d6, s3d7]
data: 
  task_type: gex_to_adt
  train_batches: [s1d1, s1d2, s2d1, s2d4]
  test_batches: [s3d6, s3d7]
  batch_correct: []
  val_size: 512
  batch_size: 256
  mod1:
    name: gex
    use_normalized: True
    scale: False
    gene_path: data/genes.csv
    gene_fraction: 0.1
    l2_norm: False
  mod2:
    name: adt
    use_normalized: True
    scale: False
    l2_norm: False
  mixup: 0.0



model:
  first_dim: [500, 250, 50]
  first_dropout: []
  first_batchnorm: [0, 1, 2, 3]
  second_dim: [100, 100]
  second_dropout: []
  second_batchnorm: [0, 1, 2, 3]
  dropout: 0.0
  enter_dropout: 0.9
  latent_dim: 25
  activation: leaky_relu
  lr: 0.001
  attack: 10
  sustain: 700
  release: 100
  gradient_clip: 1.0
  train_per_batch: True
  train_temperature: -1
  predict_temperature: 3.0
  l2_lambda: 0.0005