data: 
  dataset_name: mp/official/gex_to_adt
  task_type: gex_to_adt
  train_batches: [s1d1, s1d2, s3d6, s3d7]
  test_batches: [s2d4, s2d1]
  batch_correct: [s1d1, s2d1]
  val_size: 512
  gene_fraction: 0.1
  mod1:
    name: gex
    use_normalized: True
    scale: True
    type: float
  mod2:
    name: adt
    use_normalized: True
    scale: True
    type: float



model:
  feature_extractor_dims: [1000, 700, 500, 300]
  fe_dropout: []
  regression_dims: [100, 100]
  regression_dropout: []
  activation: leaky_relu
  lr: 0.001
  balance_classes: True
  attack: 10
  sustain: 1500
  release: 500
  batch_size: 32
  gradient_clip: 1.0

  l2_lambda: 0.0
  dropout: 0.5

  use_mmd_loss: True
  mmd_lambda: 1.0

  use_l2_loss: False
  l2_loss_lambda: 0.01

  use_coral_loss: False
  coral_lambda: 10.0

  use_critic: False
  critic_type: ganin
  critic_lambda: 0.01
  critic_gamma: 1.0
  critic_dims: [300, 300, 100]
  normal_iterations: 1
  critic_iterations: 1
  critic_lr: 0.001


  use_vi_dropout: False
  vi_lambda: 0.5
  vi_attack: 30

  do_tsne: False
  tsne_frequency: 10