# elastic net parameters
alpha: 1.0
l1_ratio: 0.5

# dataset name
data: pm/official/atac_to_gex

# preprocessing parameters
mod1:
  reduce_dim:
    n_components: 200
mod2:
  reduce_dim:
    n_components: 100