# elastic net parameters
alpha: 1.0
l1_ratio: 0.5

# dataset name
data: pm/official/gex_to_atac

# preprocessing parameters
mod1:
  reduce_dim:
    n_components: 100
mod2:
  reduce_dim:
    n_components: 200