data:
  task_type: cite
  train_batches: [s1d1, s2d4, s2d1, s3d6]
  test_batches: [s1d2, s3d7]
  mod1:
    name: gex
    use_normalized: True
    scale: True
    type: float
    gene_path: data/genes.csv
    gene_fraction: 0.1
  mod2:
    name: adt
    use_normalized: True
    scale: True
    type: float

model:
  first_dim: [2000, 1000, 500, 250, 100]
  second_dim: [100, 70, 50]
  common_dim: [100, 100]
  activation: leaky_relu
  lr: 0.01
  attack: 0
  sustain: 100
  release: 100