data: 
  dataset_name: mp/official/gex_to_adt
  task_type: gex_to_adt
  mod1:
    name: gex
    inputs:
      use_normalized: False
      scale: True
      type: float
    targets:
      use_normalized: False
      scale: False
      type: int
  mod2:
    name: adt
    inputs:
      use_normalized: False
      scale: True
      type: float
    targets:
      use_normalized: False
      scale: False
      type: int


model:
  first:
    encoder: [2000, 700, 500]
    decoder: [500, 700, 2000]
    activation: leaky_relu
    loss: nb
  second:
    encoder: [100, 100]
    decoder: [100, 100]
    activation: leaky_relu
    loss: nb
  latent_dim: 300
  lr: 0.0007
  batch_size: 128
  use_mmd_loss: False
  mmd_lambda: 0.01
  gradient_clip: 2.0
  first_to_second: 1.0
  patience: 5