data: 
  dataset_name: mp/official/gex_to_adt
  task_type: gex_to_adt
  mod1:
    name: gex
    inputs:
      use_normalized: True
      scale: True
      type: float
    targets:
      use_normalized: True
      scale: False
      type: float
  mod2:
    name: adt
    inputs:
      use_normalized: True
      scale: True
      type: float
    targets:
      use_normalized: True
      scale: False
      type: float


model:
  first:
    encoder: [2000, 750, 500]
    encoder_bn: []
    decoder: [500, 750, 1000, 2000]
    decoder_bn: []
    activation: relu
    loss: mse
  second:
    encoder: [100, 200, 300, 400]
    encoder_bn: []
    decoder: [200, 200]
    decoder_bn: []
    activation: relu
    loss: mse
  latent_dim: 500
  lr: 0.0005
  attack: 10
  sustain: 10
  release: 50
  batch_size: 128
  gradient_clip: 1.0
  patience: 40
  vae: False
  swa: False

  use_mmd_loss: False
  mmd_lambda: 0.0001

  use_sim_loss: False
  sim_lambda: 10.0

  use_critic: False
  critic_type: discriminator
  critic_lambda: 0.1
  critic_lr: 0.002
  critic_iterations: 1