data: 
  dataset_name: mp/official/gex_to_adt
  task_type: gex_to_adt
  mod1:
    name: gex
    inputs:
      use_normalized: True
      scale: False
      type: float
    targets:
      use_normalized: True
      scale: True
      type: float
  mod2:
    name: adt
    inputs:
      use_normalized: True
      scale: False
      type: float
    targets:
      use_normalized: True
      scale: False
      type: float


model:
  first:
    encoder: [300, 200, 100]
    batchnorm_pos: []
    dropout_pos: []
    dropout: 0.5
    decoder: [75, 100, 500]
    activation: leaky_relu
    loss: mse
  second:
    encoder: [40, 35]
    batchnorm_pos: []
    dropout_pos: []
    dropout: 0.7
    decoder: [100, 100]
    activation: leaky_relu
    loss: mse
  latent_dim: 40
  lr: 0.001
  batch_size: 128
  gradient_clip: 2.0
  first_to_second: 1.0
  patience: 40
  vae: False

  use_mmd_loss: False
  mmd_lambda: 0.0001

  use_sim_loss: True
  sim_lambda: 10.0

  use_critic: True
  critic_type: discriminator
  critic_lambda: 1.0
  critic_lr: 0.002
  critic_iterations: 5