data: 
  dataset_name: mp/official/gex_to_adt
  task_type: gex_to_adt
  mod1:
    name: gex
    inputs:
      use_normalized: True
      scale: True
      type: float
    targets:
      use_normalized: True
      scale: False
      type: float
  mod2:
    name: adt
    inputs:
      use_normalized: True
      scale: True
      type: float
    targets:
      use_normalized: True
      scale: False
      type: float


model:
  first:
    encoder: [2000, 700, 500]
    encoder_bn: []
    decoder: [500, 700, 2000]
    decoder_bn: []
    activation: leaky_relu
    loss: mse
    zero_decoder: []
    zero_decoder_bn: []
    p_decoder: []
    p_decoder_bn: []

  second:
    encoder: [100, 100]
    encoder_bn: []
    decoder: [100, 100]
    decoder_bn: []
    activation: relu
    loss: mse
    zero_decoder: []
    zero_decoder_bn: []
  latent_dim: 500
  lr: 0.001
  balance_classes: True
  attack: 10
  sustain: 1000
  release: 500
  batch_size: 256
  gradient_clip: 1.0
  l2_lambda: 0.0002
  patience: 40
  vae: False
  swa: False

  use_mmd_loss: False
  mmd_lambda: 0.0001

  use_sim_loss: False
  sim_lambda: 10.0

  use_critic: False
  critic_type: discriminator
  critic_lambda: 0.1
  critic_lr: 0.002
  critic_iterations: 1