data: 
  dataset_name: mp/official/gex_to_adt
  task_type: gex_to_adt
  mod1:
    name: gex
    inputs:
      top_n_genes: 2000
      use_normalized: True
      scale: True
      type: float
    targets:
      use_normalized: True
      scale: False
      type: float
  mod2:
    name: adt
    inputs:
      use_normalized: True
      scale: True
      type: float
    targets:
      use_normalized: True
      scale: False
      type: float


model:
  first:
    encoder: [2000, 1500, 1000, 1000, 750, 750, 500, 500]
    encoder_bn: [0, 1, 2, 3, 4, 5, 6, 7]
    decoder: [500, 500, 750, 750, 1000, 1500, 2000]
    decoder_bn: [0, 1, 2, 3, 4, 5, 6]
    activation: relu
    loss: zero_mse
    zero_decoder: [750, 750, 750, 750, 1000, 1500, 2000]
    zero_decoder_bn: [0, 1, 2, 3, 4, 5, 6]

  second:
    encoder: [200, 200, 300, 400]
    encoder_bn: [0, 1, 2, 3]
    decoder: [500, 500, 300]
    decoder_bn: [0, 1]
    activation: relu
    loss: zero_mse
    zero_decoder: [500, 500, 300]
    zero_decoder_bn: [0, 1,]
  latent_dim: 500
  lr: 0.002
  balance_classes: False
  attack: 10
  sustain: 300
  release: 500
  batch_size: 256
  gradient_clip: 1.0
  patience: 40
  vae: False
  swa: False

  use_mmd_loss: False
  mmd_lambda: 0.0001

  use_sim_loss: False
  sim_lambda: 10.0

  use_critic: False
  critic_type: discriminator
  critic_lambda: 0.1
  critic_lr: 0.002
  critic_iterations: 1