data: 
  dataset_name: mp/official/gex_to_adt
  mod1:
    use_normalized: True
    scale: True
  mod2:
    use_normalized: True
    scale: True


model:
  first_dims: [2000, 700, 500]
  first_bn: -1
  second_dims: [100, 100]
  latent_dim: 300
  activation: leaky_relu
  lr: 0.001
  batch_size: 128
  use_mmd_loss: False
  mmd_lambda: 0.1