data: 
  dataset_name: mp/official/gex_to_adt
  mod1:
    use_normalized: True
    scale: True
  mod2:
    use_normalized: True
    scale: True


model:
  first_dims: [2000, 700, 500]
  second_dims: [100, 100]
  latent_dim: 300
  activation: selu
  lr: 0.0005
  batch_size: 256
  use_mmd_loss: True
  mmd_lambda: 0.1