data: 
  task_type: adt_to_gex
  train_batches: [s1d1, s1d2, s2d1, s2d4]
  test_batches: [s3d6, s3d7]
  batch_correct: [s1d1, s2d1]
  val_size: 512
  batch_size: 32
  mod1:
    name: adt
    scale: True
  mod2:
    name: gex
    use_normalized: True
    scale: True



model:
  feature_extractor_dims: [150, 150, 150, 100]
  fe_dropout: []
  regression_dims: [100, 250, 500, 750, 1000, 2000]
  regression_dropout: []
  activation: leaky_relu
  lr: 0.001
  balance_classes: True
  attack: 10
  sustain: 1500
  release: 500
  gradient_clip: 1.0

  l2_lambda: 0.0001
  dropout: 0.5

  use_mmd_loss: True
  mmd_lambda: 0.5

  use_l2_loss: False
  l2_loss_lambda: 0.01

  use_coral_loss: False
  coral_lambda: 10.0

  use_critic: False
  critic_type: ganin
  critic_lambda: 0.01
  critic_gamma: 1.0
  critic_dims: [300, 300, 100]
  normal_iterations: 1
  critic_iterations: 1
  critic_lr: 0.001


  use_vi_dropout: False
  vi_lambda: 0.5
  vi_attack: 30

  do_tsne: False
  tsne_frequency: 10