data: 
  task_type: atac_to_gex
  train_batches: [s1d1, s1d2, s2d1, s2d4]
  test_batches: [s3d6, s3d7]
  batch_correct: []
  val_size: 512
  batch_size: 32
  mod1:
    name: atac
    scale: False
    mapping_file: data/region_to_gene.csv
    use_gene_activity: False
    window: 10
  mod2:
    name: gex
    use_normalized: True
    scale: False
    l2_norm: False
  mixup: 0.0


model:
  feature_extractor_dims: [2000, 2000, 1000, 1000, 500, 250, 250]
  fe_dropout: []
  fe_batchnorm: []
  regression_dims: [2000, 2000, 3000, 4000]
  regression_dropout: []
  regression_batchnorm: []
  concat_input: True
  activation: prelu
  connections: None
  lr: 0.0001
  balance_classes: True
  attack: 10
  sustain: 1500
  release: 500
  gradient_clip: 1.0
  entry_dropout:
    type: stupid
    p: 0.6
    k: -0.07
    b: 0.4
  random_scale: 0.0
  log_transform: False

  l2_lambda: 0.0
  dropout: 0.5

  use_mmd_loss: False
  mmd_lambda: 0.5

  use_l2_loss: False
  l2_loss_lambda: 0.01

  use_coral_loss: False
  coral_lambda: 10.0

  use_critic: False
  critic_type: ganin
  critic_lambda: 0.01
  critic_gamma: 1.0
  critic_dims: [300, 300, 100]
  normal_iterations: 1
  critic_iterations: 1
  critic_lr: 0.001


  use_vi_dropout: False
  vi_lambda: 0.5
  vi_attack: 30

  do_tsne: False
  tsne_frequency: 10