data: 
  task_type: gex_to_adt
  train_batches: [s1d1, s1d2, s2d1, s2d4]
  test_batches: [s3d6, s3d7]
  batch_correct: []
  val_size: 512
  batch_size: 32
  mod1:
    name: gex
    use_normalized: False
    scale: False
    gene_path: data/genes.csv
    gene_fraction: 0.1
  mod2:
    name: adt
    use_normalized: True
    scale: False
  mixup: 0.0


model:
  feature_extractor_dims: [1000, 700, 500, 300]
  fe_dropout: []
  fe_batchnorm: []
  regression_dims: [200, 200]
  regression_dropout: []
  regression_batchnorm: []
  activation: leaky_relu
  connections: None
  lr: 0.0001
  balance_classes: True
  attack: 10
  sustain: 1500
  release: 500
  gradient_clip: 1.0

  entry_dropout:
    type: bio
    p: 0.0
    max: 0.7
    elbow: 0.3
  random_scale: 0.0
  log_transform: True

  l2_lambda: 0.0
  dropout: 0.5

  use_mmd_loss: False
  mmd_lambda: 0.2

  use_l2_loss: False
  l2_loss_lambda: 0.01

  use_coral_loss: False
  coral_lambda: 10.0

  use_critic: False
  critic_type: ganin
  critic_lambda: 0.01
  critic_gamma: 1.0
  critic_dims: [300, 300, 100]
  normal_iterations: 1
  critic_iterations: 1
  critic_lr: 0.001


  use_vi_dropout: False
  vi_lambda: 0.5
  vi_attack: 30

  do_tsne: False
  tsne_frequency: 10